/**
 * nodeGrants.ts — what an EXECUTOR (one running app instance) was itself given, over which node of an
 * identity's own `.me` tree. See typedocs/architecture/page-grants-design.md (branch `design/page-grants`)
 * for the full design; this is its minimal walkthrough (§8 there), not the gateway guard.
 *
 * Deliberately general, never gateway-specific: the scope is a tree coordinate (namespace + nodePath +
 * operations), not `gatewayId`. A gateway's own control surface is just one kind of node this can name,
 * using the SAME capability vocabulary gatewayAuthority.ts's `grants` already defines (opaque strings) --
 * never a parallel one. `gatewayCapabilities.ts`'s own header already names the gap this closes: "owner:
 * 'all' describes the identity's own standing, never a license for every caller claiming to act on its
 * behalf." This is that second, caller-level layer -- and even once connected to a gateway, it is an
 * additional `AND`, never a replacement for `hasGatewayCapability`.
 *
 * Two identities involved, never conflated (design doc §2.3):
 *   - the IDENTITY granting: proven the same way every other mutation in this codebase already is --
 *     a currently-active keychain key, checked fresh (`getKeychainKey`), never cached.
 *   - the EXECUTOR acting: proven by a signature from `record.executorPublicKey`, generated by the
 *     executor itself. This proves "the same running instance that was granted this", nothing about
 *     which authored app it claims to be (that is a human-readable label only, not enforced here).
 *
 * Storage: `nodeGrants.<grantId>`, a reserved per-namespace semantic branch, placed exactly like
 * `keychain.keys` (keychain.ts) -- same write path (`appendSemanticMemory`), same reasoning: this is a
 * fact about ONE identity's own tree, not installation-scoped state the way gatewayAuthority.ts's
 * `daemon.gateways.*` is.
 */
import crypto from "node:crypto";
import { appendSemanticMemory, readSemanticValueForNamespace } from "./memoryStore.js";
import { getKeychainKey } from "./keychain.js";
import { getClaim } from "./records.js";
import { isNamespaceWriteAuthorized } from "./replay.js";
import { normalizeNamespaceIdentity } from "../namespace/identity.js";

const NODE_GRANTS_BRANCH = "nodeGrants";
const REPLAY_WINDOW_MS = 120_000; // same value as keychain.ts/gatewayAuthority.ts -- no reason to diverge

// ─── raw Ed25519 public key -> SPKI PEM ──────────────────────────────────────
// Duplicated from keychain.ts's own rawEd25519PublicKeyToPem (itself duplicated from syncHandler.ts,
// "not exported there... rather than imported across a handler/claim layering boundary") -- same fixed
// SPKI DER prefix for Ed25519 (RFC 8410), same conversion, same reason to keep a local copy: an executor's
// own generated keypair arrives the same raw base64url shape a person's device key already does, and
// verifySignature() (replay.ts) needs a real PEM key, not raw bytes.
function rawEd25519PublicKeyToPem(rawPublicKeyBase64Url: string): string | null {
  try {
    const normalized = String(rawPublicKeyBase64Url || "").replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const raw = Buffer.from(padded, "base64");
    if (raw.length !== 32) return null;
    const spkiPrefix = Buffer.from("302a300506032b6570032100", "hex");
    const spkiDer = Buffer.concat([spkiPrefix, raw]);
    const key = crypto.createPublicKey({ key: spkiDer, format: "der", type: "spki" });
    return key.export({ type: "spki", format: "pem" }).toString();
  } catch {
    return null;
  }
}

export function isNodeGrantReservedPath(pathInput: string): boolean {
  const path = String(pathInput || "").trim();
  return path === NODE_GRANTS_BRANCH || path.startsWith(`${NODE_GRANTS_BRANCH}.`);
}

export interface NodeGrantRecord {
  grantId: string;
  identityHash: string;
  namespace: string;
  nodePath: string;
  /** What the executor may do at nodePath -- plain 'read'/'write' for an ordinary semantic node, or a
   *  gateway-control node's own named capabilities when nodePath denotes one. Opaque here on purpose. */
  operations: string[];
  executorPublicKey: string;
  appLabel: string;
  grantedAt: number;
  expiresAt: number | null;
  revokedAt: number | null;
  nonce: string;
  signature: string;
}

export type NodeGrantError =
  | "NAMESPACE_REQUIRED"
  | "NODE_PATH_REQUIRED"
  | "OPERATIONS_REQUIRED"
  | "EXECUTOR_KEY_REQUIRED"
  | "GRANTING_KEY_NOT_FOUND"
  | "GRANTING_KEY_REVOKED"
  | "CLAIM_REQUIRED"
  | "PROOF_REQUIRED"
  | "PROOF_INVALID"
  | "REPLAY_REJECTED"
  | "GRANT_NOT_FOUND"
  | "ALREADY_REVOKED";

export type NodeGrantResult<T> = { ok: true; value: T } | { ok: false; error: NodeGrantError };

// Anti-replay bookkeeping, same shape as gatewayAuthority.ts's own (a bounded in-memory map, pruned past
// its own expiry window) -- a separate scope string so a grant nonce can never collide with an unrelated
// gateway-authority or keychain nonce even if the two coincidentally share a value.
const _seenNonces = new Map<string, number>();
function replayKey(scope: string, actor: string, nonce: string): string {
  return `${scope}:${actor}:${nonce}`;
}
function isReplayed(scope: string, actor: string, nonce: string): boolean {
  const expiry = _seenNonces.get(replayKey(scope, actor, nonce));
  return expiry !== undefined && expiry >= Date.now();
}
function consumeNonce(scope: string, actor: string, nonce: string): void {
  _seenNonces.set(replayKey(scope, actor, nonce), Date.now() + REPLAY_WINDOW_MS);
  if (_seenNonces.size > 10_000) {
    const now = Date.now();
    for (const [k, exp] of _seenNonces) if (exp < now) _seenNonces.delete(k);
  }
}
function isFreshTimestamp(timestamp: unknown): boolean {
  const ts = Number(timestamp);
  return Number.isFinite(ts) && Math.abs(Date.now() - ts) <= REPLAY_WINDOW_MS;
}

/** Reset for tests -- same purpose as keychain.ts's/gatewayAuthority.ts's own reset helpers. */
export function resetNodeGrantNonceCacheForTests(): void {
  _seenNonces.clear();
}

function normalizeNodePath(input: unknown): string {
  return String(input ?? "")
    .trim()
    .replace(/^\.+/, "")
    .replace(/\.+$/, "")
    .replace(/\.{2,}/g, ".");
}

/** Is `target` the granted node itself, or a genuine sub-path of it? The same prefix-safety
 *  semanticBranchReader.test.ts already requires for the kernel's own branch reads: "dashboard" must not
 *  match "dashboardX" -- only "dashboard" itself or something starting with "dashboard.". An empty
 *  `nodePath` denotes the whole tree, so it matches everything. */
export function nodePathCovers(nodePath: string, target: string): boolean {
  const scope = normalizeNodePath(nodePath);
  const t = normalizeNodePath(target);
  if (!t) return false;
  if (!scope) return true;
  return t === scope || t.startsWith(`${scope}.`);
}

function readRecord(namespace: string, grantId: string): NodeGrantRecord | null {
  const record = readSemanticValueForNamespace(namespace, `${NODE_GRANTS_BRANCH}.${grantId}`);
  return record && typeof record === "object" ? (record as NodeGrantRecord) : null;
}

function persist(record: NodeGrantRecord): void {
  appendSemanticMemory({ namespace: record.namespace, path: `${NODE_GRANTS_BRANCH}.${record.grantId}`, data: record });
}

export interface GrantNodeAccessInput {
  /** Client-generated (the runtime mints this, the same way it already mints a nonce) -- grantNodeAccess
   *  does NOT mint its own, because the signed payload below must be constructable BEFORE the call (the
   *  server cannot sign anything on the identity's behalf), so the id cannot be something only the server
   *  learns afterward. Rejected if a record already exists under it. */
  grantId: string;
  namespace: string;
  nodePath: string;
  operations: string[];
  /** Raw base64url Ed25519 public key, the same wire shape a keychain device key arrives in --
   *  converted to PEM here before storage, never expected pre-converted. */
  executorPublicKey: string;
  appLabel?: string;
  expiresAt?: number | null;
  /** The GRANTING identity's own proof -- an active keychain key, same "vigencia" check every other
   *  mutation in this codebase already requires. */
  grantingKeyId: string;
  nonce: string;
  timestamp: number;
  signature: string;
  signedPayload?: string;
}

/** The identity approves an executor's request (design doc §4) -- signed by the identity's own active
 *  keychain key, never something an executor can produce for itself. */
export function grantNodeAccess(input: GrantNodeAccessInput): NodeGrantResult<NodeGrantRecord> {
  const namespace = normalizeNamespaceIdentity(input.namespace);
  if (!namespace) return { ok: false, error: "NAMESPACE_REQUIRED" };
  const nodePath = normalizeNodePath(input.nodePath);
  const operations = Array.isArray(input.operations) ? input.operations.map(String).filter(Boolean) : [];
  if (operations.length === 0) return { ok: false, error: "OPERATIONS_REQUIRED" };
  const executorPublicKeyPem = rawEd25519PublicKeyToPem(String(input.executorPublicKey || "").trim());
  if (!executorPublicKeyPem) return { ok: false, error: "EXECUTOR_KEY_REQUIRED" };

  const grantingKeyId = String(input.grantingKeyId || "").trim();
  const key = getKeychainKey(namespace, grantingKeyId);
  if (!key) return { ok: false, error: "GRANTING_KEY_NOT_FOUND" };
  if (key.authorization !== "active") return { ok: false, error: "GRANTING_KEY_REVOKED" };

  const claim = getClaim(namespace);
  if (!claim) return { ok: false, error: "CLAIM_REQUIRED" };

  if (!input.nonce || !input.signature) return { ok: false, error: "PROOF_REQUIRED" };
  if (!isFreshTimestamp(input.timestamp)) return { ok: false, error: "PROOF_INVALID" };
  if (isReplayed("node-grant", grantingKeyId, input.nonce)) return { ok: false, error: "REPLAY_REJECTED" };

  const grantId = String(input.grantId || "").trim();
  if (!grantId) return { ok: false, error: "EXECUTOR_KEY_REQUIRED" }; // reuses this error; a missing id is as unusable as a missing key
  if (readRecord(namespace, grantId)) return { ok: false, error: "REPLAY_REJECTED" }; // an existing record under this id -- never silently overwritten

  // Signed over the RAW executor key, never the PEM form: the caller only ever knows the raw base64url
  // bytes it generated (same convention keychain.ts's own key-registration signing already uses for
  // `newKey.publicKey`) -- rawEd25519PublicKeyToPem() above is a storage-time conversion only, computed
  // here, never something the signer could have produced itself before this call existed.
  const signedFields = {
    op: "node-grant",
    namespace,
    nodePath,
    operations,
    executorPublicKey: String(input.executorPublicKey || "").trim(),
    grantId,
    nonce: input.nonce,
    timestamp: input.timestamp,
  };
  const authorized = isNamespaceWriteAuthorized({
    claimIdentityHash: grantingKeyId,
    claimPublicKey: key.publicKey,
    body: { ...signedFields, signature: input.signature, signedPayload: input.signedPayload },
  });
  if (!authorized) return { ok: false, error: "PROOF_INVALID" };

  consumeNonce("node-grant", grantingKeyId, input.nonce);

  const record: NodeGrantRecord = {
    grantId,
    identityHash: claim.identityHash,
    namespace,
    nodePath,
    operations,
    executorPublicKey: executorPublicKeyPem,
    appLabel: String(input.appLabel || "").trim(),
    grantedAt: Date.now(),
    expiresAt: input.expiresAt ?? null,
    revokedAt: null,
    nonce: input.nonce,
    signature: input.signature,
  };
  persist(record);
  return { ok: true, value: record };
}

export interface RevokeNodeAccessInput {
  namespace: string;
  grantId: string;
  grantingKeyId: string;
  nonce: string;
  timestamp: number;
  signature: string;
  signedPayload?: string;
}

/** Kept, never deleted (design doc §3): §7's live-revocation guarantee needs a record to still exist so
 *  the very next check on it fails, not a lookup that silently finds nothing and might be read as "never
 *  existed" rather than "existed, then was revoked". */
export function revokeNodeAccess(input: RevokeNodeAccessInput): NodeGrantResult<NodeGrantRecord> {
  const namespace = normalizeNamespaceIdentity(input.namespace);
  if (!namespace) return { ok: false, error: "NAMESPACE_REQUIRED" };
  const grantId = String(input.grantId || "").trim();
  const record = readRecord(namespace, grantId);
  if (!record) return { ok: false, error: "GRANT_NOT_FOUND" };
  if (record.revokedAt) return { ok: false, error: "ALREADY_REVOKED" };

  const grantingKeyId = String(input.grantingKeyId || "").trim();
  const key = getKeychainKey(namespace, grantingKeyId);
  if (!key) return { ok: false, error: "GRANTING_KEY_NOT_FOUND" };
  if (key.authorization !== "active") return { ok: false, error: "GRANTING_KEY_REVOKED" };

  if (!input.nonce || !input.signature) return { ok: false, error: "PROOF_REQUIRED" };
  if (!isFreshTimestamp(input.timestamp)) return { ok: false, error: "PROOF_INVALID" };
  if (isReplayed("node-grant-revoke", grantingKeyId, input.nonce)) return { ok: false, error: "REPLAY_REJECTED" };

  const signedFields = { op: "node-grant-revoke", namespace, grantId, nonce: input.nonce, timestamp: input.timestamp };
  const authorized = isNamespaceWriteAuthorized({
    claimIdentityHash: grantingKeyId,
    claimPublicKey: key.publicKey,
    body: { ...signedFields, signature: input.signature, signedPayload: input.signedPayload },
  });
  if (!authorized) return { ok: false, error: "PROOF_INVALID" };

  consumeNonce("node-grant-revoke", grantingKeyId, input.nonce);

  const revoked: NodeGrantRecord = { ...record, revokedAt: Date.now() };
  persist(revoked);
  return { ok: true, value: revoked };
}

export function readNodeGrant(namespaceInput: string, grantId: string): NodeGrantRecord | null {
  const namespace = normalizeNamespaceIdentity(namespaceInput);
  if (!namespace || !grantId) return null;
  return readRecord(namespace, grantId);
}

/** Not revoked, not expired, `operation` included, and `target` genuinely within `nodePath` -- the one
 *  question every action should reduce to (design doc §5), before even checking the executor's signature. */
export function nodeGrantAllows(record: NodeGrantRecord | null, operation: string, target: string): boolean {
  if (!record) return false;
  if (record.revokedAt) return false;
  if (record.expiresAt !== null && Date.now() > record.expiresAt) return false;
  if (!record.operations.includes(operation)) return false;
  return nodePathCovers(record.nodePath, target);
}

export interface ExecutorActionInput {
  grantId: string;
  operation: string;
  target: string;
  params?: unknown;
  nonce: string;
  timestamp: number;
  signature: string;
  signedPayload?: string;
}

export type ExecutorActionError = NodeGrantError | "NOT_GRANTED";
export type ExecutorActionResult = { ok: true; value: NodeGrantRecord } | { ok: false; error: ExecutorActionError };

/** Verifies an executor's own signature over the EXACT action it is performing (design doc §5: operation,
 *  target and params are all part of what is signed, so a read signature can never be replayed as a write,
 *  and a signature for one node can never be replayed against another). Does not perform the action
 *  itself -- callers do that only after this returns ok. */
export function verifyExecutorAction(
  namespaceInput: string,
  input: ExecutorActionInput
): ExecutorActionResult {
  const namespace = normalizeNamespaceIdentity(namespaceInput);
  if (!namespace) return { ok: false, error: "NAMESPACE_REQUIRED" };
  const record = readRecord(namespace, String(input.grantId || "").trim());
  if (!record) return { ok: false, error: "GRANT_NOT_FOUND" };

  const target = normalizeNodePath(input.target);
  if (!nodeGrantAllows(record, input.operation, target)) {
    return { ok: false, error: record.revokedAt || (record.expiresAt !== null && Date.now() > record.expiresAt)
      ? "GRANT_NOT_FOUND" // expired/revoked reads the same as "nothing here" to the executor -- fail closed, no distinction that could leak whether a grant once existed
      : "NOT_GRANTED" };
  }

  if (!input.nonce || !input.signature) return { ok: false, error: "PROOF_REQUIRED" };
  if (!isFreshTimestamp(input.timestamp)) return { ok: false, error: "PROOF_INVALID" };
  if (isReplayed(`node-grant-act:${record.grantId}`, record.executorPublicKey, input.nonce)) {
    return { ok: false, error: "REPLAY_REJECTED" };
  }

  const signedFields = {
    op: "node-grant-act",
    grantId: record.grantId,
    namespace,
    nodePath: record.nodePath,
    operation: input.operation,
    target,
    params: input.params ?? null,
    nonce: input.nonce,
    timestamp: input.timestamp,
  };
  const authorized = isNamespaceWriteAuthorized({
    claimIdentityHash: record.executorPublicKey, // not a person's identityHash -- isNamespaceWriteAuthorized
    claimPublicKey: record.executorPublicKey,     // only needs "this public key signed this body", which is
    body: { ...signedFields, signature: input.signature, signedPayload: input.signedPayload }, // exactly the executor proof
  });
  if (!authorized) return { ok: false, error: "PROOF_INVALID" };

  consumeNonce(`node-grant-act:${record.grantId}`, record.executorPublicKey, input.nonce);
  return { ok: true, value: record };
}
